(()=>{const $=id=>document.getElementById(id),c=$('ink-canvas'),g=c.getContext('2d');let w=1000,h=650,last=0,t=0,run=false,score=0,lives=4,wave=1,charge=0,player=150,invul=0,aim={x:700,y:250},keys={},shots=[],enemies=[],barrels=[],sparks=[],timer=0,boss=null,muted=true,audio,shotClock=0;const ink='#28558a',red='#aa514c',purple='#7c5d91';
function size(){const r=c.getBoundingClientRect();w=r.width;h=r.height;const d=Math.min(devicePixelRatio,1.7);c.width=w*d;c.height=h*d;g.setTransform(d,0,0,d,0,0);player=Math.min(player,w*.7)}new ResizeObserver(size).observe(c);size();const sea=x=>h*.66+Math.sin(x*.017+t*1.4)*9+Math.sin(x*.006-t)*5;
function line(points,color=ink,width=1){g.strokeStyle=color;g.lineWidth=width;g.beginPath();points.forEach(([x,y],i)=>i?g.lineTo(x,y):g.moveTo(x,y));g.stroke()}function poly(points,color=ink,fill='#f8f7e9'){g.fillStyle=fill;g.beginPath();points.forEach(([x,y],i)=>i?g.lineTo(x,y):g.moveTo(x,y));g.closePath();g.fill();g.strokeStyle=color;g.lineWidth=1.2;g.stroke();for(let j=0;j<2;j++)line(points.map(([x,y])=>[x+Math.sin(x+j)*.65,y+Math.cos(y+j)*.6]),color,.45)}
function ship(x,y,color=ink,scale=1,angle=0){g.save();g.translate(x,y);g.rotate(angle);g.scale(scale,scale);poly([[-48,-7],[45,-7],[32,14],[-30,17],[-48,-7]],color);for(let i=-35;i<33;i+=6)line([[i,-5],[i+14,11]],color,.6);line([[-43,3],[39,3]],color);for(const [mx,high] of [[-18,59],[8,77],[30,50]]){line([[mx,6],[mx,-high]],color,1.5);poly([[mx-20,-high+9],[mx+15,-high+9],[mx+19,-high+32],[mx-24,-high+32]],color);poly([[mx-21,-high+35],[mx+15,-high+35],[mx+22,-high+53],[mx-25,-high+53]],color);for(let i=-16;i<17;i+=5)line([[mx+i,-high+11],[mx+i+3,-high+29]],color,.45);line([[mx,-high],[-35,6]],color,.4);line([[mx,-high],[35,6]],color,.4);poly([[mx,-high],[mx+17,-high+4],[mx,-high+8]],color)}for(let i=-25;i<30;i+=13){g.beginPath();g.arc(i,4,2,0,7);g.stroke()}g.restore()}
function cloud(x,y,s=1){g.save();g.translate(x,y);g.scale(s,s);g.fillStyle='#f8f7e9';g.strokeStyle=ink;g.lineWidth=.8;g.beginPath();g.moveTo(-35,10);g.bezierCurveTo(-52,-3,-29,-17,-19,-9);g.bezierCurveTo(-24,-35,9,-35,13,-15);g.bezierCurveTo(29,-29,43,-8,33,-2);g.bezierCurveTo(53,-5,53,14,28,14);g.closePath();g.fill();g.stroke();for(let i=-32;i<35;i+=2)line([[i,3+Math.sin(i)*3],[i+9,12]],ink,.35);g.restore()}
function update(){$('ink-score').textContent=`Vague ${wave} · ${lives} vies · Score ${score} · Encre ${Math.floor(charge)} %`;c.dataset.score=score;c.dataset.wave=wave;c.dataset.lives=lives;c.dataset.running=run;}
function sound(freq=130){if(muted)return;audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),v=audio.createGain();o.type='triangle';o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(35,audio.currentTime+.15);v.gain.setValueAtTime(.08,audio.currentTime);v.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.18);o.connect(v).connect(audio.destination);o.start();o.stop(audio.currentTime+.19)}
function start(){run=true;score=0;lives=4;wave=1;charge=0;player=w*.2;shots=[];enemies=[];barrels=[];sparks=[];boss=null;timer=0;invul=0;$('ink-start').textContent='Recommencer';spawn();update()}
function spawn(){for(let i=0;i<Math.min(5,1+wave);i++)enemies.push({x:w*.8+i*170,hp:wave>=5?4:2,fire:1.5+i*.6,speed:14+wave*3,color:wave>=5?'#32263e':red});barrels.push({x:w*.55+Math.random()*w*.3});if(wave%3===0)boss={x:w*.78,hp:5+wave,phase:0};}
function shoot(){if(!run||shotClock>0)return;const py=sea(player)-30,dx=aim.x-player,dy=aim.y-py,len=Math.hypot(dx,dy)||1;shots.push({x:player,y:py,vx:dx/len*330,vy:dy/len*330-25,friend:true,bounces:0});shotClock=.28;sound(170);c.dataset.shots=shots.length;}
function explosion(x,y,color=red){for(let i=0;i<22;i++){const a=Math.random()*7,s=35+Math.random()*100;sparks.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.4+Math.random()*.6,color})}sound(80)}
function damage(){if(invul>0)return;lives--;invul=1.5;explosion(player,sea(player),ink);if(lives<=0){run=false;$('ink-start').textContent='Reprendre la mer'}update()}
function burst(){if(!run||charge<100)return;charge=0;for(const e of enemies){e.hp-=3;explosion(e.x,sea(e.x))}if(boss)boss.hp-=4;shots=shots.filter(s=>s.friend);update()}
c.onpointermove=e=>{const r=c.getBoundingClientRect();aim={x:e.clientX-r.left,y:e.clientY-r.top}};c.onpointerdown=e=>{const r=c.getBoundingClientRect();aim={x:e.clientX-r.left,y:e.clientY-r.top};if(!run)start();else shoot()};window.addEventListener('keydown',e=>{if(/INPUT|SELECT/.test(e.target.tagName))return;if(['q','d','a','ArrowLeft','ArrowRight',' '].includes(e.key)){e.preventDefault();keys[e.key]=true;if(e.key===' ')burst()}});window.addEventListener('keyup',e=>keys[e.key]=false);window.addEventListener('blur',()=>keys={});for(const [id,key] of [['ink-left','q'],['ink-right','d']]){$(id).onpointerdown=e=>{e.preventDefault();e.target.setPointerCapture(e.pointerId);keys[key]=true};$(id).onpointerup=$(id).onpointercancel=()=>keys[key]=false}$('ink-burst').onclick=burst;$('ink-start').onclick=start;$('ink-sound').onclick=e=>{muted=!muted;e.target.textContent=muted?'Son : non':'Son : oui';e.target.setAttribute('aria-pressed',!muted);if(!muted)sound(200)};
function frame(now){const dt=Math.min(.035,(now-last)/1000||.016);last=now;t+=dt;if(run){timer+=dt;shotClock=Math.max(0,shotClock-dt);invul=Math.max(0,invul-dt);charge=Math.min(100,charge+dt*3);player=Math.max(50,Math.min(w-50,player+((keys.d||keys.ArrowRight?1:0)-(keys.q||keys.a||keys.ArrowLeft?1:0))*135*dt));for(const e of enemies){e.x-=e.speed*dt;e.fire-=dt;if(e.fire<0){e.fire=2+Math.random()*2;const dx=player-e.x;shots.push({x:e.x,y:sea(e.x)-35,vx:Math.sign(dx)*(100+wave*4),vy:-100-Math.random()*65,friend:false,bounces:0})}if(Math.abs(e.x-player)<50||e.x<-60){e.hp=0;damage()}}
for(let i=shots.length-1;i>=0;i--){const s=shots[i];s.x+=s.vx*dt;s.y+=s.vy*dt;s.vy+=95*dt;let remove=false;if(s.y>sea(s.x)){if(s.friend&&s.bounces<2&&Math.abs(s.vy)<160){s.y=sea(s.x)-2;s.vy=-Math.abs(s.vy)*.7;s.bounces++}else remove=true}if(s.friend){for(const e of enemies)if(e.hp>0&&Math.abs(s.x-e.x)<40&&s.y>sea(e.x)-75&&s.y<sea(e.x)+15){e.hp--;score+=75;charge=Math.min(100,charge+12);explosion(s.x,s.y);remove=true;break}if(boss&&Math.abs(s.x-boss.x)<26&&s.y>sea(boss.x)-140){boss.hp--;remove=true;score+=100;explosion(s.x,s.y,purple)}for(let j=barrels.length-1;j>=0;j--)if(Math.hypot(s.x-barrels[j].x,s.y-(sea(barrels[j].x)-8))<22){const bx=barrels[j].x;explosion(bx,sea(bx),'#c07b39');for(const e of enemies)if(Math.abs(e.x-bx)<170)e.hp-=3;barrels.splice(j,1);score+=150;remove=true}}else if(Math.abs(s.x-player)<35&&s.y>sea(player)-65&&s.y<sea(player)+10){damage();remove=true}if(s.x<-60||s.x>w+80||s.y>h+40)remove=true;if(remove)shots.splice(i,1)}enemies=enemies.filter(e=>{if(e.hp<=0){score+=100;explosion(e.x,sea(e.x));return false}return true});if(boss){boss.phase+=dt;if(Math.abs(player-boss.x)<38&&Math.sin(boss.phase)>0)damage();if(boss.hp<=0){explosion(boss.x,sea(boss.x),purple);score+=500;boss=null}}if(!enemies.length&&!boss&&timer>2){wave++;timer=0;spawn()}update()}
g.fillStyle='#f8f7e9';g.fillRect(0,0,w,h);g.strokeStyle='#dce1d4';g.lineWidth=.6;for(let y=15;y<h;y+=24){g.beginPath();g.moveTo(0,y);g.lineTo(w,y);g.stroke()}g.strokeStyle='#e6b6aa';g.beginPath();g.moveTo(45,0);g.lineTo(45,h);g.stroke();for(let i=0;i<4;i++)cloud((i*w/3+t*3)%(w+130)-65,115+(i%2)*42,.65+i*.1);g.strokeStyle='#c58b4c';g.beginPath();g.arc(w*.83,150,21,0,7);g.stroke();for(let a=0;a<6.3;a+=.32)line([[w*.83+Math.cos(a)*26,150+Math.sin(a)*26],[w*.83+Math.cos(a)*35,150+Math.sin(a)*35]],'#c58b4c');
for(let j=0;j<6;j++){const pts=[];for(let xx=0;xx<=w;xx+=7)pts.push([xx,sea(xx)+j*25+Math.sin(xx*.022+j)*j]);line(pts,ink,j===0?1.5:.4)}for(let i=0;i<2;i++){const px=i?w*.91:w*.09,py=h*.57;line([[px,py],[px+5,py-55]],'#4c7755',2);for(let k=0;k<7;k++){const a=k/7*6.2;const end=[px+Math.cos(a)*32,py-55+Math.sin(a)*22];line([[px+5,py-55],end],'#4c7755',1);for(let z=0;z<6;z++)line([[px+5+(end[0]-px-5)*z/6,py-55+(end[1]-py+55)*z/6],[px+(end[0]-px)*z/6+7,py-47+(end[1]-py+55)*z/6]],'#4c7755',.5)}}
for(const px of [w*.04,w*.68,w*.94]){const py=h*.59;poly([[px-25,py],[px-10,py-35],[px-2,py-5],[px+13,py-25],[px+26,py]],ink);for(let j=0;j<12;j++)line([[px-15+j*3,py-18],[px-8+j*3,py]],ink,.4)}const lx=w*.93,ly=h*.58;poly([[lx-11,ly],[lx-6,ly-63],[lx+6,ly-63],[lx+12,ly]],red);for(let j=0;j<4;j++)line([[lx-9,ly-j*14],[lx+8,ly-j*14]],red,3);poly([[lx-10,ly-63],[lx,ly-76],[lx+10,ly-63]],red);if(wave>=3){for(let j=0;j<5;j++)cloud(w*j/4,82,.95);if(run)for(let j=0;j<60;j++){const rx=(j*43+t*95)%w,ry=(j*71+t*180)%(h*.55);line([[rx,ry],[rx-19,ry+23]],'#797982',.35)}}
if(boss){const bx=boss.x,by=sea(bx);g.strokeStyle=purple;g.lineWidth=18;g.beginPath();g.moveTo(bx+20,by);g.bezierCurveTo(bx-35,by-55,bx+50,by-150,bx-10,by-138);g.stroke();for(let j=0;j<12;j++){g.strokeStyle='#f8f7e9';g.lineWidth=2;g.beginPath();g.arc(bx+Math.sin(j*.6)*12,by-j*10,3,0,7);g.stroke()}}
for(const b of barrels){const y=sea(b.x)-10;poly([[b.x-9,y-13],[b.x+9,y-13],[b.x+10,y+12],[b.x-10,y+12]],red);line([[b.x-9,y-6],[b.x+9,y-6]],red);line([[b.x-9,y+6],[b.x+9,y+6]],red)}for(const e of enemies)ship(e.x,sea(e.x),e.color,e.hp>3?1.6:1.25,Math.sin(t+e.x)*.06);if(invul===0||Math.floor(t*10)%2)ship(player,sea(player),ink,1.25,Math.sin(t+player)*.045);for(const s of shots){g.fillStyle=s.friend?ink:purple;g.beginPath();g.arc(s.x,s.y,3.5,0,7);g.fill();line([[s.x-s.vx*.035,s.y-s.vy*.035],[s.x,s.y]],s.friend?ink:purple,.5)}for(let i=sparks.length-1;i>=0;i--){const s=sparks[i];s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;line([[s.x,s.y],[s.x-s.vx*.06,s.y-s.vy*.06]],s.color,1);if(s.life<0)sparks.splice(i,1)}g.strokeStyle=red;g.lineWidth=.8;g.beginPath();g.arc(aim.x,aim.y,8,0,7);g.stroke();line([[aim.x-13,aim.y],[aim.x+13,aim.y]],red);line([[aim.x,aim.y-13],[aim.x,aim.y+13]],red);if(!run){g.fillStyle='#f8f7e9e8';g.fillRect(w*.2,h*.3,w*.6,90);g.fillStyle=ink;g.font='24px Georgia';g.textAlign='center';g.fillText(lives<=0?'Navire coulé — à toi de rejouer':'Prends la mer sur une page de cahier',w/2,h*.3+35);g.font='15px Georgia';g.fillText('Clique pour commencer',w/2,h*.3+65);g.textAlign='left'}requestAnimationFrame(frame)}update();requestAnimationFrame(frame);})();
