(()=>{const c=document.getElementById('wood-canvas'),g=c.getContext('2d'),img=new Image();img.src='firewood-pastel.png';let w=0,h=0,dpr=1,t0=0,chop=-1,count=0,muted=false,ctx,pan=0,down=null;const chips=[];
const noise=document.createElement('canvas');noise.width=noise.height=180;const ng=noise.getContext('2d');for(let i=0;i<12000;i++){ng.fillStyle=i%2?'rgba(242,226,183,.12)':'rgba(13,25,21,.15)';ng.fillRect(Math.random()*180,Math.random()*180,1+Math.random()*4,1+Math.random()*2)}const grain=g.createPattern(noise,'repeat');
function size(){const r=c.getBoundingClientRect();w=r.width;h=r.height;dpr=Math.min(devicePixelRatio,1.6);c.width=w*dpr;c.height=h*dpr;}new ResizeObserver(size).observe(c);size();
function sound(){if(muted)return;ctx??=new(window.AudioContext||window.webkitAudioContext)();ctx.resume();let b=ctx.createBuffer(1,ctx.sampleRate*.24,ctx.sampleRate),a=b.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=(Math.random()*2-1)*Math.exp(-i/(ctx.sampleRate*.037));const n=ctx.createBufferSource(),f=ctx.createBiquadFilter(),v=ctx.createGain();n.buffer=b;f.type='lowpass';f.frequency.value=1700;v.gain.value=.65;n.connect(f).connect(v).connect(ctx.destination);n.start();const o=ctx.createOscillator(),ov=ctx.createGain();o.frequency.setValueAtTime(150,ctx.currentTime);o.frequency.exponentialRampToValueAtTime(48,ctx.currentTime+.12);ov.gain.setValueAtTime(.22,ctx.currentTime);ov.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.16);o.connect(ov).connect(ctx.destination);o.start();o.stop(ctx.currentTime+.18);}
function hit(){if(chop>=0)return;chop=performance.now();count++;document.getElementById('wood-count').textContent=count+' bûche'+(count>1?'s':'');setTimeout(sound,150);for(let i=0;i<38;i++)chips.push({x:0,y:-90,vx:(Math.random()-.5)*450,vy:-100-Math.random()*230,life:1+Math.random(),size:2+Math.random()*8});c.dataset.chops=count;}
c.onpointerdown=e=>{down={x:e.clientX,pan};c.setPointerCapture(e.pointerId)};c.onpointermove=e=>{if(down)pan=Math.max(-90,Math.min(90,down.pan+(e.clientX-down.x)*.35));};c.onpointerup=e=>{if(down&&Math.abs(e.clientX-down.x)<8)hit();down=null};c.onkeydown=e=>{if(e.code==='Space'){e.preventDefault();hit()}};document.getElementById('wood-sound').onclick=e=>{muted=!muted;e.target.textContent=muted?'Son : non':'Son : oui';e.target.setAttribute('aria-pressed',!muted)};
function shape(points,color){g.fillStyle=color;g.beginPath();points.forEach(([x,y],i)=>i?g.lineTo(x,y):g.moveTo(x,y));g.closePath();g.fill();g.fillStyle=grain;g.fill();}
function log(x,y,rot=0){g.save();g.translate(x,y);g.rotate(rot);shape([[-35,0],[-31,-115],[25,-120],[38,-7]],'#5d513d');shape([[-26,-7],[-20,-111],[0,-116],[-4,-3]],'#a3946b');g.fillStyle='#bfaf7d';g.beginPath();g.ellipse(0,-117,29,12,0,0,Math.PI*2);g.fill();g.strokeStyle='#766b50';for(let i=1;i<4;i++){g.beginPath();g.ellipse(0,-117,i*7,i*2.5,0,0,Math.PI*2);g.stroke()}g.fillStyle=grain;g.fillRect(-30,-128,60,130);g.restore();}
function frame(t){const dt=Math.min(.035,(t-t0)/1000||.016);t0=t;g.setTransform(dpr,0,0,dpr,0,0);g.clearRect(0,0,w,h);if(img.complete&&img.naturalWidth){const k=Math.max(w/img.width,h/img.height);g.drawImage(img,(w-img.width*k)/2+pan*.14,(h-img.height*k)/2,img.width*k,img.height*k)}g.save();g.translate(w*.53+pan,h*.71);const scale=Math.min(w/720,h/520);g.scale(scale,scale);g.fillStyle='rgba(12,23,17,.45)';g.beginPath();g.ellipse(12,75,150,36,0,0,7);g.fill();shape([[-108,-4],[-98,91],[-67,109],[96,92],[113,0]],'#4f4a3b');for(let i=0;i<22;i++)shape([[-100+i*9,0],[-96+i*9,87],[-89+i*9,94],[-93+i*9,0]],i%2?'#6f6851':'#343f32');g.fillStyle='#a69d76';g.beginPath();g.ellipse(0,0,113,42,0,0,7);g.fill();g.strokeStyle='#716e50';for(let i=1;i<7;i++){g.beginPath();g.ellipse(0,0,i*15,i*5.5,.03,0,7);g.stroke()}g.fillStyle=grain;g.fill();const age=chop<0?-1:(t-chop)/1000;if(age<.16)log(0,-5);else if(age<1.1){log(-Math.min(170,(age-.16)*210),-5+(age-.16)*60,-(age-.16)*1.9);log(Math.min(170,(age-.16)*210),-5+(age-.16)*60,(age-.16)*1.9)}else{chop=-1;log(0,-5)}if(age>=0&&age<.45){g.save();g.translate(60,-150);g.rotate(-1.4+Math.min(1,age/.16)*1.6);shape([[-6,-130],[7,-130],[5,110],[-5,110]],'#a88656');shape([[-5,-125],[62,-141],[71,-96],[5,-83]],'#a8b6ad');g.restore()}for(let i=chips.length-1;i>=0;i--){const p=chips[i];p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=450*dt;g.globalAlpha=Math.min(1,p.life);g.fillStyle=i%2?'#beab78':'#7e7152';g.fillRect(p.x,p.y,p.size,p.size*.5);if(p.life<=0)chips.splice(i,1)}g.globalAlpha=1;g.restore();requestAnimationFrame(frame)}requestAnimationFrame(frame);})();
