import * as THREE from './three.module.js';
const canvas=document.getElementById('wood-canvas'),host=canvas.parentElement,renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.setClearColor('#dedbea');const scene=new THREE.Scene();scene.fog=new THREE.Fog('#dedbea',18,52);const camera=new THREE.PerspectiveCamera(48,1,.1,80);scene.add(camera);scene.add(new THREE.HemisphereLight('#fff3e6','#b4a9bd',2));const sun=new THREE.DirectionalLight('#fff0df',2.4);sun.position.set(-6,13,5);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-12,right:12,top:12,bottom:-12});scene.add(sun);
function texture(colors,bark=false){const c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d');x.fillStyle=colors[0];x.fillRect(0,0,256,256);for(let i=0;i<6500;i++){x.fillStyle=colors[i%colors.length];x.globalAlpha=.15+Math.random()*.5;x.fillRect(Math.random()*256,Math.random()*256,bark?1+Math.random()*5:1+Math.random()*10,bark?8+Math.random()*45:1+Math.random()*4)}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.wrapS=t.wrapT=THREE.RepeatWrapping;return t;}
const groundTex=texture(['#b9c9b3','#cbd7b7','#e4d9b9','#a7bdad','#d3d9b4']);groundTex.repeat.set(18,18);const ground=new THREE.Mesh(new THREE.PlaneGeometry(100,100),new THREE.MeshStandardMaterial({map:groundTex,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
const bark=new THREE.MeshStandardMaterial({map:texture(['#ad8f85','#c6a59a','#dec3aa','#967f87'],true),roughness:1}),cut=new THREE.MeshStandardMaterial({map:texture(['#ecd3b5','#d7b995','#f5e1c7']),roughness:1});const stump=new THREE.Mesh(new THREE.CylinderGeometry(.85,1, .65,24),[bark,cut,cut]);stump.position.y=.325;stump.castShadow=stump.receiveShadow=true;scene.add(stump);
for(let j=1;j<9;j++){const ring=new THREE.Mesh(new THREE.TorusGeometry(j*.087,.003,3,64),new THREE.MeshBasicMaterial({color:'#7d7754',transparent:true,opacity:.48}));ring.rotation.x=-Math.PI/2;ring.position.y=.654;scene.add(ring)}
// A real clearing with depth and moving grass.
const grass=[],bladeGeo=new THREE.BufferGeometry();bladeGeo.setAttribute('position',new THREE.Float32BufferAttribute([-.045,0,0,.045,0,0,.02,.28,.015,-.03,.28,.015,.02,.28,.015,.055,.53,.04],3));bladeGeo.computeVertexNormals();const grassMesh=new THREE.InstancedMesh(bladeGeo,new THREE.MeshStandardMaterial({color:'#c2d5b6',side:THREE.DoubleSide,roughness:1}),2400),dummy=new THREE.Object3D();for(let i=0;i<2400;i++){let x=(Math.random()-.5)*24,z=(Math.random()-.5)*24;if(Math.hypot(x,z)<1.25)x+=2;grass.push({x,z,angle:Math.random()*7,phase:Math.random()*7,scale:.5+Math.random()});grassMesh.setColorAt(i,new THREE.Color(['#a5c5b5','#c4d4b0','#a5b6bd','#e1d4b2'][i%4]));}scene.add(grassMesh);
for(let i=0;i<60;i++){const a=Math.random()*7,r=10+Math.random()*25,x=Math.cos(a)*r,z=Math.sin(a)*r,h=7+Math.random()*9;const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.16,.35,h,7),bark);trunk.position.set(x,h/2,z);scene.add(trunk);const crown=new THREE.Mesh(new THREE.IcosahedronGeometry(2+Math.random()*2,1),new THREE.MeshStandardMaterial({color:i%2?'#b3c7b9':'#c6cbb1',roughness:1,flatShading:true}));crown.position.set(x,h,z);scene.add(crown)}
// First-person tool modelled in Blender (tools/blender-axe.py): shaft along +Y, bit toward -Z, thickness along X.
const axe=new THREE.Group(),woodMat=new THREE.MeshStandardMaterial({color:'#b98567',roughness:.86}),steelMat=new THREE.MeshStandardMaterial({color:'#ffffff',metalness:.45,roughness:.42,vertexColors:true});
const cuttingEdge=new THREE.Vector3(0,1.17,-.475);
fetch('timber-axe.json?v=20260921-3').then(r=>r.json()).then(model=>{
 for(const [name,part] of Object.entries(model)){if(!part.position)continue;const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(part.position,3));geo.setAttribute('normal',new THREE.Float32BufferAttribute(part.normal,3));
  if(name!=='handle'){const colors=[],poll=new THREE.Color('#8e9cab'),bit=new THREE.Color('#f4f7fa');for(let i=0;i<part.position.length;i+=3){const z=part.position[i+2],u=THREE.MathUtils.clamp((-.30-z)/.17,0,1);const col=poll.clone().lerp(bit,u*u);colors.push(col.r,col.g,col.b);}geo.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));}
  const mesh=new THREE.Mesh(geo,name==='handle'?woodMat:steelMat);mesh.castShadow=true;axe.add(mesh);}
 cuttingEdge.fromArray(model.edge.point);
});
scene.add(axe);
// Poses are expressed relative to the camera: grip position, shaft direction and edge direction.
// The shaft runs along local +Y and the cutting edge points along local -Z.
const restPose={position:new THREE.Vector3(),quaternion:new THREE.Quaternion()},raisedPose={position:new THREE.Vector3(),quaternion:new THREE.Quaternion()},hitPose={position:new THREE.Vector3(),quaternion:new THREE.Quaternion()};
const tmpX=new THREE.Vector3(),tmpY=new THREE.Vector3(),tmpZ=new THREE.Vector3(),tmpM=new THREE.Matrix4(),tmpEdge=new THREE.Vector3(),tmpHands=new THREE.Vector3();
function orient(pose,shaft,edge){tmpY.copy(shaft).normalize();tmpZ.copy(edge).negate();tmpZ.addScaledVector(tmpY,-tmpY.dot(tmpZ)).normalize();tmpX.crossVectors(tmpY,tmpZ).normalize();tmpM.makeBasis(tmpX,tmpY,tmpZ);pose.quaternion.setFromRotationMatrix(tmpM);}
function cameraPose(pose,grip,shaft,edge){pose.position.copy(grip).applyMatrix4(camera.matrixWorld);orient(pose,tmpY.copy(shaft).applyQuaternion(camera.quaternion),tmpEdge.copy(edge).applyQuaternion(camera.quaternion));}
// At impact the grip lies on the line from the log toward the viewer's hands, at the axe's own reach,
// and the head rolls so the edge bites as vertically as the shaft allows.
const tmpU=new THREE.Vector3(),tmpW=new THREE.Vector3();
function strikePose(pose,target){const reach=Math.hypot(cuttingEdge.y,cuttingEdge.z),bite=Math.atan2(-cuttingEdge.z,cuttingEdge.y);tmpHands.set(.45,-.62,-.8).applyMatrix4(camera.matrixWorld);tmpU.subVectors(target,tmpHands).normalize();tmpW.set(0,-1,0).addScaledVector(tmpU,-tmpU.dot(new THREE.Vector3(0,-1,0))).normalize();
 tmpY.copy(tmpU).multiplyScalar(Math.cos(bite)).addScaledVector(tmpW,-Math.sin(bite));tmpZ.copy(tmpU).multiplyScalar(-Math.sin(bite)).addScaledVector(tmpW,-Math.cos(bite));tmpX.crossVectors(tmpY,tmpZ).normalize();tmpM.makeBasis(tmpX,tmpY,tmpZ);pose.quaternion.setFromRotationMatrix(tmpM);
 pose.position.copy(target).addScaledVector(tmpU,-reach);}
let orbit=.15,pitch=0,drag=null,chargeAt=null,active=[],flying=[],pile=[],cuts=0,targetCuts=3,logs=0,swing=null,shake=0,muted=false,audio=null,birdAt=0;
const area=p=>Math.abs(p.reduce((s,a,i)=>{const b=p[(i+1)%p.length];return s+a[0]*b[1]-b[0]*a[1]},0)/2);
function mesh(poly,height){const shape=new THREE.Shape();poly.forEach((p,i)=>i?shape.lineTo(p[0],p[1]):shape.moveTo(p[0],p[1]));shape.closePath();const geo=new THREE.ExtrudeGeometry(shape,{depth:height,bevelEnabled:false});geo.rotateX(-Math.PI/2);const m=new THREE.Mesh(geo,[cut,bark]);m.castShadow=m.receiveShadow=true;m.userData={poly,height};return m;}
function spawn(){cuts=0;targetCuts=2+Math.floor(Math.random()*4);const radius=.30+Math.random()*.26,height=.34+Math.random()*.26,n=18,poly=Array.from({length:n},(_,i)=>{const a=i/n*Math.PI*2,r=radius*(.97+Math.random()*.06);return[Math.cos(a)*r,Math.sin(a)*r]});const m=mesh(poly,height);m.position.y=.66;scene.add(m);active=[m];canvas.dataset.requiredCuts=targetCuts;update()}
function update(){document.getElementById('wood-count').textContent=logs+' bûche'+(logs>1?'s':'')+' · '+pile.length+' morceau'+(pile.length>1?'x':'')+' · coupe '+cuts+'/'+targetCuts;canvas.dataset.pile=pile.length;canvas.dataset.cuts=cuts;canvas.dataset.logs=logs;}
function clip(poly,n,offset,sign){const out=[];for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length],da=(a[0]*n[0]+a[1]*n[1]-offset)*sign,db=(b[0]*n[0]+b[1]*n[1]-offset)*sign;if(da>=0)out.push(a);if((da>=0)!==(db>=0)){const t=da/(da-db);out.push([a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t])}}return out}
function eject(m){flying.push({m,v:new THREE.Vector3((Math.random()-.5)*3,1+Math.random(),(Math.random()-.5)*3),spin:new THREE.Vector3(Math.random()*3,Math.random()*3,Math.random()*3),time:0});}
function impact(){if(!active.length)return;cuts++;const old=active.reduce((a,b)=>area(a.userData.poly)>area(b.userData.poly)?a:b),poly=old.userData.poly,c=poly.reduce((s,p)=>[s[0]+p[0]/poly.length,s[1]+p[1]/poly.length],[0,0]),a=orbit,n=[Math.cos(a),Math.sin(a)],off=c[0]*n[0]+c[1]*n[1];active=active.filter(m=>m!==old);scene.remove(old);for(const sign of [-1,1]){const p=clip(poly,n,off,sign);if(p.length<3)continue;const m=mesh(p,old.userData.height);m.position.copy(old.position);m.position.x+=n[0]*sign*.022;m.position.z-=n[1]*sign*.022;scene.add(m);active.push(m)}old.geometry.dispose();shake=.055;chopSound();if(cuts>=targetCuts){for(const m of active)eject(m);active=[];logs++;setTimeout(spawn,1100)}update()}
function initAudio(){if(audio)return;const C=window.AudioContext||window.webkitAudioContext;audio=new C();audio.resume();}
function chirp(){if(!audio||muted)return;const t=audio.currentTime;for(let j=0;j<3;j++){const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(1900+Math.random()*1000,t+j*.13);o.frequency.exponentialRampToValueAtTime(3100+Math.random()*800,t+j*.13+.08);g.gain.setValueAtTime(.0001,t+j*.13);g.gain.exponentialRampToValueAtTime(.018,t+j*.13+.02);g.gain.exponentialRampToValueAtTime(.0001,t+j*.13+.11);o.connect(g).connect(audio.destination);o.start(t+j*.13);o.stop(t+j*.13+.12)}}
function chopSound(){if(!audio||muted)return;const buf=audio.createBuffer(1,audio.sampleRate*.3,audio.sampleRate),a=buf.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=(Math.random()*2-1)*Math.exp(-i/(audio.sampleRate*.025))*(i%31?1:2);const s=audio.createBufferSource(),f=audio.createBiquadFilter(),g=audio.createGain();s.buffer=buf;f.type='lowpass';f.frequency.value=900+Math.random()*1400;g.gain.value=.55;s.connect(f).connect(g).connect(audio.destination);s.start();const o=audio.createOscillator(),v=audio.createGain();o.frequency.setValueAtTime(140+Math.random()*60,audio.currentTime);o.frequency.exponentialRampToValueAtTime(45,audio.currentTime+.14);v.gain.setValueAtTime(.3,audio.currentTime);v.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.18);o.connect(v).connect(audio.destination);o.start();o.stop(audio.currentTime+.2)}
function strike(){initAudio();if(swing||!active.length)return;const log=active.reduce((a,b)=>area(a.userData.poly)>area(b.userData.poly)?a:b);const center=log.userData.poly.reduce((v,p)=>v.add(new THREE.Vector3(p[0],0,-p[1])),new THREE.Vector3()).divideScalar(log.userData.poly.length);center.add(log.position);center.y+=log.userData.height;swing={t:performance.now(),hit:false,target:center,from:axe.position.clone(),rotation:axe.quaternion.clone()};canvas.dataset.phase='armer';}
canvas.oncontextmenu=e=>e.preventDefault();
canvas.onpointerdown=e=>{e.preventDefault();canvas.focus();canvas.setPointerCapture(e.pointerId);if(e.button===2){drag={x:e.clientX,y:e.clientY,orbit,pitch};}else if(e.button===0&&!swing){initAudio();chargeAt=performance.now();canvas.dataset.phase='armer';}};
canvas.onpointermove=e=>{if(drag){orbit=drag.orbit+(e.clientX-drag.x)*.006;pitch=THREE.MathUtils.clamp(drag.pitch+(e.clientY-drag.y)*.002,-.2,.3);}};
const cancel=()=>{drag=null;chargeAt=null;};canvas.onpointercancel=canvas.onlostpointercapture=cancel;window.addEventListener('blur',cancel);
canvas.onpointerup=e=>{if(e.button===0&&chargeAt!==null){chargeAt=null;strike();}drag=null;};
canvas.onkeydown=e=>{if(e.code==='ArrowLeft'||e.code==='KeyQ'||e.code==='KeyA'){e.preventDefault();orbit-=.09;}else if(e.code==='ArrowRight'||e.code==='KeyD'){e.preventDefault();orbit+=.09;}else if(e.code==='ArrowUp'){e.preventDefault();pitch=THREE.MathUtils.clamp(pitch-.05,-.2,.3);}else if(e.code==='ArrowDown'){e.preventDefault();pitch=THREE.MathUtils.clamp(pitch+.05,-.2,.3);}if(e.code==='Space'){e.preventDefault();if(!e.repeat&&!swing){chargeAt=performance.now();canvas.dataset.phase='armer';}}};canvas.onkeyup=e=>{if(e.code==='Space'){e.preventDefault();chargeAt=null;strike();}};
document.getElementById('wood-new').onclick=()=>{for(const m of active){scene.remove(m);m.geometry.dispose();}active=[];swing=null;chargeAt=null;spawn();};
document.getElementById('wood-sound').onclick=e=>{initAudio();muted=!muted;e.target.textContent=muted?'Son : non':'Son : oui';e.target.setAttribute('aria-pressed',!muted)};
const resize=()=>{const r=host.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()};new ResizeObserver(resize).observe(host);resize();spawn();let last=0;
function frame(t){const dt=Math.min(.035,(t-last)/1000||.016);last=t;camera.position.set(Math.sin(orbit)*1.55,2.3+pitch,Math.cos(orbit)*1.55);camera.lookAt(0,1.0+pitch*.35,0);if(shake>.001){camera.position.x+=(Math.random()-.5)*shake;camera.position.y+=(Math.random()-.5)*shake;shake*=.83}camera.updateMatrixWorld();
cameraPose(restPose,new THREE.Vector3(.44,-.78,-1.15),new THREE.Vector3(-.22,.92,-.32),new THREE.Vector3(-.4,0,-1));
cameraPose(raisedPose,new THREE.Vector3(.34,-.42,-.95),new THREE.Vector3(.08,.84,.52),new THREE.Vector3(0,.6,-1));
if(swing){const p=(t-swing.t)/1100;strikePose(hitPose,swing.target);if(p>=.53&&!swing.hit){swing.hit=true;impact();canvas.dataset.phase='impact';}
 if(p<.30){const u=p/.30,ease=u*u*(3-2*u);axe.position.lerpVectors(swing.from,raisedPose.position,ease);axe.quaternion.slerpQuaternions(swing.rotation,raisedPose.quaternion,ease);}
 else if(p<.53){const u=(p-.30)/.23,ease=u*u;axe.position.lerpVectors(raisedPose.position,hitPose.position,ease);axe.quaternion.slerpQuaternions(raisedPose.quaternion,hitPose.quaternion,ease);canvas.dataset.phase='frapper';}
 else if(p<.66){axe.position.copy(hitPose.position);axe.quaternion.copy(hitPose.quaternion);}
 else{const u=Math.min(1,(p-.66)/.34),ease=u*u*(3-2*u);axe.position.lerpVectors(hitPose.position,restPose.position,ease);axe.quaternion.slerpQuaternions(hitPose.quaternion,restPose.quaternion,ease);canvas.dataset.phase='retirer';}
 if(p>=1){swing=null;canvas.dataset.phase='repos';}
}else{const u=chargeAt===null?0:Math.min(1,(t-chargeAt)/650),ease=u*u*(3-2*u);axe.position.lerpVectors(restPose.position,raisedPose.position,ease);axe.quaternion.slerpQuaternions(restPose.quaternion,raisedPose.quaternion,ease);}
grass.forEach((b,i)=>{dummy.position.set(b.x,0,b.z);dummy.rotation.set(0,b.angle,Math.sin(t*.0015+b.phase)*.15);dummy.scale.setScalar(b.scale);dummy.updateMatrix();grassMesh.setMatrixAt(i,dummy.matrix)});grassMesh.instanceMatrix.needsUpdate=true;for(let i=flying.length-1;i>=0;i--){const p=flying[i];p.time+=dt;p.v.y-=5*dt;p.m.position.addScaledVector(p.v,dt);p.m.rotation.x+=p.spin.x*dt;p.m.rotation.z+=p.spin.z*dt;if(p.m.position.y<.12||p.time>2){const idx=pile.length;p.m.position.set(1.7+(idx%4)*.23,.14+Math.floor((idx%64)/4)*.11,-.6+Math.floor(idx/64)*.75);p.m.rotation.set(Math.PI/2,0,(Math.floor(idx/4)%2)*Math.PI/2);pile.push(p.m);flying.splice(i,1);if(pile.length>120){const old=pile.shift();scene.remove(old);old.geometry.dispose()}update()}}if(audio&&t>birdAt){birdAt=t+4000+Math.random()*6500;chirp()}renderer.render(scene,camera);requestAnimationFrame(frame)}window.addEventListener('keydown',e=>{if(e.target!==canvas&&!/INPUT|SELECT|BUTTON|TEXTAREA/.test(e.target.tagName)&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Space','KeyQ','KeyD','KeyA'].includes(e.code))canvas.onkeydown(e);});window.addEventListener('keyup',e=>{if(e.target!==canvas&&e.code==='Space')canvas.onkeyup(e);});canvas.dataset.ready='true';requestAnimationFrame(frame);
