import * as THREE from './three.module.js';

const stage=document.getElementById('sandboard-stage');
const canvas=document.getElementById('sandboard-canvas');
const reset=document.getElementById('sandboard-reset');
const fallback=document.getElementById('sandboard-fallback');

if(stage&&canvas&&reset){
  try{
    const palette={sand:new THREE.Color('#ffa62f'),coral:new THREE.Color('#ef4b2f'),red:new THREE.Color('#c8102e'),green:new THREE.Color('#07583d'),ink:new THREE.Color('#071b16'),blue:new THREE.Color('#9db4bd')};
    const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});
    renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.75));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;
    const scene=new THREE.Scene();scene.background=palette.coral;
    const camera=new THREE.PerspectiveCamera(38,1,.1,40);camera.position.set(0,-4.2,10.8);camera.lookAt(0,0,0);
    scene.add(new THREE.HemisphereLight(0xffe0a0,0x063628,2.25));
    const sun=new THREE.DirectionalLight(0xfff1c8,3.6);sun.position.set(-7,-5,5.5);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);scene.add(sun);

    const sx=260,sy=184,geometry=new THREE.PlaneGeometry(34,24,sx,sy),position=geometry.attributes.position;
    const base=new Float32Array(position.count),colors=new Float32Array(position.count*3),tempColor=new THREE.Color();
    const grain=(x,y)=>Math.sin(x*2.1+y*.7)*.035+Math.sin(y*4.3-x*.8)*.018+Math.sin((x+y)*8.2)*.008;
    const paletteGroove=new THREE.Color('#9c2a16'),paletteRidge=new THREE.Color('#ffd76a'),paletteDust=new THREE.Color('#ff8f2a');
    // Gouache shading of the relief: grooves sink into a dark red, pushed-up ridges catch a warm yellow.
    const recolor=()=>{for(let i=0;i<position.count;i++){const depth=base[i]-position.getZ(i);tempColor.set('#ffffff');if(depth>.02)tempColor.lerp(paletteGroove,Math.min(1,(depth-.02)/.3)*.9);else if(depth<-.015)tempColor.lerp(paletteRidge,Math.min(1,(-depth-.015)/.12)*.75);tempColor.offsetHSL(0,0,(Math.sin(i*12.33)*.5+.5)*.055-.025);colors[i*3]=tempColor.r;colors[i*3+1]=tempColor.g;colors[i*3+2]=tempColor.b;}geometry.setAttribute('color',new THREE.BufferAttribute(colors,3));geometry.attributes.color.needsUpdate=true;};
    for(let i=0;i<position.count;i++){base[i]=grain(position.getX(i),position.getY(i));position.setZ(i,base[i]);}
    recolor();geometry.computeVertexNormals();
    // Relief baked in Blender (tools/blender-sand.py): wind ripples, dunes and grains drive the resting heights.
    const heightImage=new Image();heightImage.src='sand-height.png?v=20260921-2';heightImage.onload=()=>{const hc=document.createElement('canvas');hc.width=heightImage.width;hc.height=heightImage.height;const hx=hc.getContext('2d');hx.drawImage(heightImage,0,0);const data=hx.getImageData(0,0,hc.width,hc.height).data;for(let i=0;i<position.count;i++){const u=(position.getX(i)+17)/34,v=(12-position.getY(i))/24;const px=Math.min(hc.width-1,Math.max(0,Math.round(u*(hc.width-1)))),py=Math.min(hc.height-1,Math.max(0,Math.round(v*(hc.height-1))));const h=data[(py*hc.width+px)*4]/255;const carved=position.getZ(i)-base[i];base[i]=(h-.5)*.16;position.setZ(i,base[i]+carved);}position.needsUpdate=true;geometry.computeVertexNormals();recolor();};
    const normalMap=new THREE.TextureLoader().load('sand-normal.png?v=20260921-2');normalMap.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());
    // Coarse, broken brush marks: gusts paint new strokes instead of a repeating wave.
    const paintCanvas=document.createElement('canvas');paintCanvas.width=1536;paintCanvas.height=1024;
    const paint=paintCanvas.getContext('2d');paint.fillStyle='#ee4b2d';paint.fillRect(0,0,1536,1024);
    function brush(x,y,length,width,angle,color,alpha=1){paint.save();paint.translate(x,y);paint.rotate(angle);paint.strokeStyle=color;paint.globalAlpha=alpha;paint.lineCap='butt';
      for(let b=0;b<36;b++){const oy=(Math.random()-.5)*width,start=Math.random()*length*.18,end=length*(.65+Math.random()*.35);paint.lineWidth=.5+Math.random()*width/14;paint.beginPath();paint.moveTo(start,oy);paint.lineTo(end,oy+(Math.random()-.5)*width*.2);paint.stroke();}paint.restore();}
    for(let n=0;n<200;n++)brush(Math.random()*1536,Math.random()*1024,50+Math.random()*250,8+Math.random()*42,-.5+Math.random()*.5,n%7===0?'#ce3426':n%3===0?'#f99728':'#ffb23b',.25+Math.random()*.6);
    const paintedImage=new Image();paintedImage.src='sand-painted.png';paintedImage.onload=()=>{paint.drawImage(paintedImage,0,0,1536,1024);paintTexture.needsUpdate=true;};const paintTexture=new THREE.CanvasTexture(paintCanvas);paintTexture.colorSpace=THREE.SRGBColorSpace;paintTexture.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());
    let gusts=[],nextGust=0,lastPaint=0;const windPaint=t=>{if(t<lastPaint+.085)return;lastPaint=t;
      if(t>nextGust){nextGust=t+.6+Math.random()*2.7;gusts.push({x:-300+Math.random()*1536,y:Math.random()*1024,angle:-.7+Math.random()*1.2,speed:16+Math.random()*32,life:12+Math.random()*22,width:12+Math.random()*45,phase:Math.random()*6.3,color:Math.random()>.25?'#ffaf36':'#ef622b'});}
      if(!gusts.length)return;paint.fillStyle='rgba(236,72,40,0.013)';paint.fillRect(0,0,1536,1024);
      gusts=gusts.filter(g=>g.life-->0);for(const g of gusts){g.x+=Math.cos(g.angle)*g.speed;g.y+=Math.sin(g.angle)*g.speed;brush(g.x,g.y,90+Math.random()*130,g.width,g.angle+(Math.random()-.5)*.09,g.color,.24);windSculpt(g);}paintTexture.needsUpdate=true;};
    // The wind also reshapes the relief: it fills old grooves, lays fresh ripples across its path and lifts a few grains.
    const windSculpt=g=>{const wx=g.x/1536*34-17,wy=12-g.y/1024*24,radius=.9+g.width*.03,r2=radius*radius,ca=Math.cos(g.angle),sa=-Math.sin(g.angle);if(wx<-17||wx>17||wy<-12||wy>12)return;const minC=Math.max(0,Math.floor((wx-radius+17)/34*sx)),maxC=Math.min(sx,Math.ceil((wx+radius+17)/34*sx)),minR=Math.max(0,Math.floor((12-wy-radius)/24*sy)),maxR=Math.min(sy,Math.ceil((12-wy+radius)/24*sy));for(let row=minR;row<=maxR;row++)for(let col=minC;col<=maxC;col++){const i=row*(sx+1)+col,dx=position.getX(i)-wx,dy=position.getY(i)-wy,d=dx*dx+dy*dy;if(d>=r2)continue;const f=(1-Math.sqrt(d)/radius)*.5,across=-dx*sa+dy*ca,z=position.getZ(i),ripple=base[i]+Math.sin(across*7.5+g.phase)*.028;position.setZ(i,z+(ripple-z)*.07*f);}dirty=true;if(Math.random()<.35)burst(new THREE.Vector3(wx,wy,surfaceAt(wx,wy)),.6);};
    const material=new THREE.MeshStandardMaterial({map:paintTexture,normalMap,normalScale:new THREE.Vector2(1.1,1.1),vertexColors:true,roughness:.98,metalness:0,flatShading:false});
    const sand=new THREE.Mesh(geometry,material);sand.receiveShadow=true;scene.add(sand);

    const tool=new THREE.Group(); // invisible pointer: no utensil
    const palmCanvas=document.createElement('canvas');palmCanvas.width=palmCanvas.height=768;const pc=palmCanvas.getContext('2d');
    // Broad, broken gouache gestures, avoiding a regular comb silhouette.
    pc.fillStyle='#073b29';pc.beginPath();pc.moveTo(680,800);pc.bezierCurveTo(580,610,545,403,372,258);pc.lineTo(338,282);pc.bezierCurveTo(470,453,500,656,608,800);pc.fill();
    const fronds=[[-280,-160],[-130,-236],[52,-229],[262,-118],[313,17],[210,168],[44,235],[-123,173],[-274,39]];
    for(let f=0;f<fronds.length;f++){const [ex,ey]=fronds[f];pc.save();pc.translate(360,270);pc.rotate(Math.atan2(ey,ex));const len=Math.hypot(ex,ey);pc.fillStyle=f%3?'#073b29':'#0e5033';pc.beginPath();pc.moveTo(-9,-8);pc.bezierCurveTo(len*.3,-46,len*.73,-62,len,-10);pc.bezierCurveTo(len*.67,-14,len*.31,27,0,16);pc.fill();for(let j=0;j<5;j++){const x=30+j*len*.15;pc.beginPath();pc.moveTo(x,-21);pc.lineTo(x+42,-57-j*2);pc.lineTo(x+55,-52);pc.lineTo(x+24,6);pc.lineTo(x+65,42-j*5);pc.lineTo(x+53,49-j*4);pc.lineTo(x-5,8);pc.fill();}pc.restore();}
    pc.globalCompositeOperation='source-atop';for(let n=0;n<8200;n++){pc.globalAlpha=.10+Math.random()*.3;pc.fillStyle=n%6?'#147149':'#d88b34';const x=Math.random()*768,y=Math.random()*768;pc.fillRect(x,y,2+Math.random()*20,.6+Math.random()*3)}pc.globalCompositeOperation='source-over';
    const palmTexture=new THREE.CanvasTexture(palmCanvas);palmTexture.colorSpace=THREE.SRGBColorSpace;
    const palm=new THREE.Mesh(new THREE.PlaneGeometry(10,10),new THREE.MeshBasicMaterial({map:palmTexture,transparent:true,opacity:.64,depthWrite:false,depthTest:false,color:palette.green}));palm.renderOrder=5;palm.position.set(3.7,1.7,.6);palm.rotation.z=-.26;scene.add(palm);

    const particleCount=5000,particleGeo=new THREE.BufferGeometry(),particlePos=new Float32Array(particleCount*3),particleVel=new Float32Array(particleCount*3),particleCol=new Float32Array(particleCount*3),particleRest=new Float32Array(particleCount);for(let i=0;i<particleCount;i++)particlePos[i*3+2]=-20;particleGeo.setAttribute('position',new THREE.BufferAttribute(particlePos,3));particleGeo.setAttribute('color',new THREE.BufferAttribute(particleCol,3));
    const grainCanvas=document.createElement('canvas');grainCanvas.width=grainCanvas.height=32;const gx=grainCanvas.getContext('2d');gx.fillStyle='#fff';gx.beginPath();gx.moveTo(6,14);gx.lineTo(15,4);gx.lineTo(27,11);gx.lineTo(25,25);gx.lineTo(10,28);gx.closePath();gx.fill();const grainTexture=new THREE.CanvasTexture(grainCanvas);
    const grainColors=[new THREE.Color('#ffd76a'),new THREE.Color('#ffa62f'),new THREE.Color('#ef4b2f'),new THREE.Color('#fff1c8')];
    const particles=new THREE.Points(particleGeo,new THREE.PointsMaterial({map:grainTexture,alphaTest:.4,vertexColors:true,size:.11,transparent:true,opacity:.95,sizeAttenuation:true}));scene.add(particles);let particleCursor=0;
    const surfaceAt=(x,y)=>{const col=Math.round((x+17)/34*sx),row=Math.round((12-y)/24*sy);if(col<0||col>sx||row<0||row>sy)return -1;return position.getZ(row*(sx+1)+col);};
    const burst=(p,speed)=>{const amount=Math.min(90,18+Math.floor(speed*4));for(let j=0;j<amount;j++){const i=particleCursor++%particleCount,a=Math.random()*Math.PI*2,r=Math.random()*.26,c=grainColors[(Math.random()*4)|0];particlePos[i*3]=p.x+Math.cos(a)*r;particlePos[i*3+1]=p.y+Math.sin(a)*r;particlePos[i*3+2]=p.z+.08;particleVel[i*3]=(Math.random()-.5)*(.07+speed*.06);particleVel[i*3+1]=(Math.random()-.5)*(.07+speed*.06);particleVel[i*3+2]=.05+Math.random()*(.06+speed*.018);particleRest[i]=0;particleCol[i*3]=c.r;particleCol[i*3+1]=c.g;particleCol[i*3+2]=c.b;}particleGeo.attributes.color.needsUpdate=true;};

    const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();let drawing=false,lastPoint=null,lastTime=0,audio=null;
    const initAudio=()=>{if(audio)return;const Ctx=window.AudioContext||window.webkitAudioContext;if(!Ctx)return;const context=new Ctx(),buffer=context.createBuffer(1,context.sampleRate,context.sampleRate),data=buffer.getChannelData(0);let brown=0;for(let i=0;i<data.length;i++){brown=(brown+(Math.random()*2-1)*.08)/1.04;data[i]=brown*.9;}const source=context.createBufferSource(),filter=context.createBiquadFilter(),gain=context.createGain();source.buffer=buffer;source.loop=true;filter.type='bandpass';filter.frequency.value=720;filter.Q.value=.7;gain.gain.value=.0001;source.connect(filter).connect(gain).connect(context.destination);source.start();audio={context,filter,gain};};
    let muted=false;document.getElementById('sandboard-sound')?.addEventListener('click',e=>{muted=!muted;e.currentTarget.textContent=muted?'Son : non':'Son : oui';e.currentTarget.setAttribute('aria-pressed',String(!muted));if(audio)audio.gain.gain.setTargetAtTime(.0001,audio.context.currentTime,.02);});
    const sound=(active,speed=0)=>{if(!audio)return;const t=audio.context.currentTime;audio.filter.frequency.setTargetAtTime(500+Math.min(speed,18)*62,t,.035);audio.gain.gain.setTargetAtTime(active&&!muted?.28+Math.min(speed,18)*.014:.0001,t,.045);};
    const hit=e=>{const r=canvas.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-((e.clientY-r.top)/r.height*2-1));raycaster.setFromCamera(pointer,camera);return raycaster.intersectObject(sand,false)[0]?.point||null;};
    let dirty=false;const sculpt=(p,speed)=>{canvas.dataset.drawn='true';const radius=.62+Math.min(speed,15)*.03,r2=radius*radius;const minC=Math.max(0,Math.floor((p.x-radius*1.5+17)/34*sx)),maxC=Math.min(sx,Math.ceil((p.x+radius*1.5+17)/34*sx)),minR=Math.max(0,Math.floor((12-p.y-radius*1.5)/24*sy)),maxR=Math.min(sy,Math.ceil((12-p.y+radius*1.5)/24*sy));for(let row=minR;row<=maxR;row++)for(let col=minC;col<=maxC;col++){const i=row*(sx+1)+col;const dx=position.getX(i)-p.x,dy=position.getY(i)-p.y,d=dx*dx+dy*dy;if(d<r2){const f=1-Math.sqrt(d)/radius;const current=position.getZ(i);position.setZ(i,Math.max(base[i]-.55,current-.09*f*f));}else if(d<r2*2.6){const f=1-Math.abs(Math.sqrt(d)-radius*1.15)/(radius*.6);if(f>0)position.setZ(i,Math.min(base[i]+.19,position.getZ(i)+.02*f));}}dirty=true;burst(p,speed);};
    canvas.addEventListener('pointermove',e=>{const p=hit(e);if(!p)return;tool.visible=true;tool.position.set(p.x,p.y,p.z+.16);const now=performance.now(),speed=lastPoint?Math.min(20,p.distanceTo(lastPoint)/Math.max(8,now-lastTime)*160):0;if(drawing){const steps=lastPoint?Math.min(24,Math.max(1,Math.ceil(p.distanceTo(lastPoint)/.10))):1;for(let j=1;j<=steps;j++)sculpt(lastPoint?lastPoint.clone().lerp(p,j/steps):p,speed);sound(true,speed);clearTimeout(sound.stopTimer);sound.stopTimer=setTimeout(()=>sound(false),100);}lastPoint=p.clone();lastTime=now;});
    canvas.addEventListener('pointerenter',()=>tool.visible=true);canvas.addEventListener('pointerleave',()=>{tool.visible=false;drawing=false;sound(false)});
    canvas.addEventListener('pointerdown',e=>{if(e.button!==0)return;e.preventDefault();initAudio();audio?.context.resume();drawing=true;canvas.setPointerCapture(e.pointerId);const p=hit(e);if(p){sculpt(p,1);lastPoint=p.clone();lastTime=performance.now();}sound(true,1)});
    const stop=()=>{drawing=false;lastPoint=null;clearTimeout(sound.stopTimer);sound(false)};canvas.addEventListener('pointerup',stop);canvas.addEventListener('pointercancel',stop);canvas.addEventListener('lostpointercapture',stop);window.addEventListener('blur',stop);
    reset.addEventListener('click',()=>{canvas.dataset.drawn='false';for(let i=0;i<position.count;i++)position.setZ(i,base[i]);position.needsUpdate=true;geometry.computeVertexNormals();recolor();for(let i=0;i<particleCount;i++)particlePos[i*3+2]=-20;particleGeo.attributes.position.needsUpdate=true;});
    const resize=()=>{const r=stage.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();};new ResizeObserver(resize).observe(stage);resize();
    const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,clock=new THREE.Clock();
    const render=()=>{const t=clock.getElapsedTime();if(dirty){position.needsUpdate=true;geometry.computeVertexNormals();recolor();dirty=false;}if(!reduced){windPaint(t);palm.rotation.z=-.26+Math.sin(t*.55)*.045;palm.scale.x=1+Math.sin(t*.7)*.035;tool.rotation.z=Math.sin(t*2)*.08;}for(let i=0;i<particleCount;i++){if(particlePos[i*3+2]<-5)continue;if(particleRest[i]>0){if(++particleRest[i]>900)particlePos[i*3+2]=-20;continue;}particlePos[i*3]+=particleVel[i*3];particlePos[i*3+1]+=particleVel[i*3+1];particlePos[i*3+2]+=particleVel[i*3+2];particleVel[i*3+2]-=.0024;const ground=surfaceAt(particlePos[i*3],particlePos[i*3+1]);if(ground<-5)particlePos[i*3+2]=-20;else if(particleVel[i*3+2]<0&&particlePos[i*3+2]<=ground+.03){particlePos[i*3+2]=ground+.03;particleRest[i]=1+((Math.random()*300)|0);}}particleGeo.attributes.position.needsUpdate=true;renderer.render(scene,camera);requestAnimationFrame(render);};canvas.dataset.ready='true';render();
  }catch(error){console.error(error);fallback.hidden=false;canvas.style.cursor='crosshair';}
}

