import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {fileURLToPath,pathToFileURL} from 'node:url';
import path from 'node:path';
const {chromium}=await import(process.env.PLAYWRIGHT_PACKAGE?pathToFileURL(process.env.PLAYWRIGHT_PACKAGE).href:'playwright');
const root=fileURLToPath(new URL('../',import.meta.url)),output=path.resolve(root,process.env.SCENE_TEST_OUTPUT||'test-results');await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_EXECUTABLE,args:['--enable-webgl','--use-angle='+(process.env.SCENE_WEBGL_BACKEND||'swiftshader'),'--enable-unsafe-swiftshader']});
const context=await browser.newContext({viewport:{width:960,height:720}}),page=await context.newPage(),errors=[],requests=[],evidence={};page.setDefaultTimeout(60000);
page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));
const harness="<!doctype html><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><script type=\"importmap\">{\"imports\":{\"three\":\"./vendor/three.module.min.js\",\"three/addons/\":\"./vendor/\"}}</script><body style=\"margin:0;background:#ededeb\"><button id=\"power\">Démarrer PS1</button><button id=\"open\">Ouvrir écran</button><script type=\"module\">\nimport * as T from 'three';import {GLTFLoader} from 'three/addons/GLTFLoader.js';import {createRetroSet} from './js/retro.js';import {createPS1Sound} from './js/ps1-sound.js';import {initUI} from './js/ui.js';\nconst tvModel=await new GLTFLoader().loadAsync('./assets/magnavox-tv-user-v43.glb');window.sound=createPS1Sound();window.retro=createRetroSet({tvModel,sound});initUI();\nconst scene=new T.Scene();retro.group.children.filter(o=>o!==retro.tv).forEach(o=>o.visible=false);scene.add(retro.group,new T.HemisphereLight(0xffffff,0x999999,3));const key=new T.DirectionalLight(0xffffff,3);key.position.set(2,4,5);scene.add(key);\nconst camera=new T.PerspectiveCamera(35,960/650,.01,50);camera.position.set(0,.53,1.9);camera.lookAt(new T.Vector3(0,.27,0));window.testCamera=camera;window.testScene=scene;const renderer=new T.WebGLRenderer({antialias:true,alpha:true});renderer.setSize(960,650);document.body.append(renderer.domElement);window.renderer=renderer;\nconst clock=new T.Clock();function frame(){requestAnimationFrame(frame);retro.update(clock.getDelta());renderer.render(scene,camera);}frame();\npower.onclick=()=>retro.powerOn();document.getElementById('open').onclick=()=>{sound.openMenu();window.dispatchEvent(new CustomEvent('room-open',{detail:{kind:'retro'}}));};\nwindow.addEventListener('ps1-ui',e=>{const a=e.detail.action;if(a==='action')sound.action();else if(a==='menu-on')sound.menu(true);else if(a==='menu-off')sound.menu(false);});\nwindow.addEventListener('room-close',()=>{retro.powerOff();sound.exit();});\n</script>";
const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.jpg':'image/jpeg','.glb':'model/gltf-binary','.mp3':'audio/mpeg','.mp4':'video/mp4'};
await context.route('**/*',async route=>{const u=new URL(route.request().url());if((route.request().isNavigationRequest()&&u.pathname!=='/ps1.html')||u.hostname!=='scene.test')return route.fulfill({body:'<!doctype html><p>Game frame</p>',contentType:'text/html'});if(u.pathname==='/ps1.html')return route.fulfill({body:harness,contentType:'text/html'});try{await route.fulfill({body:await readFile(path.join(root,decodeURIComponent(u.pathname))),contentType:types[path.extname(u.pathname)]||'application/octet-stream'});}catch{return route.fulfill({status:404,body:u.pathname});}});
try{
 await page.goto('http://scene.test/ps1.html');await page.waitForFunction(()=>window.retro);await page.locator('#power').click();await page.waitForFunction(()=>retro.bootVideo.currentTime>1);
 evidence.boot=await page.evaluate(()=>({duration:retro.bootDuration,videoDuration:retro.bootVideo.duration,rate:retro.bootVideo.playbackRate,muted:retro.bootVideo.muted,map:retro.screen.material.map.isVideoTexture,sound:sound.state.startupEvents}));
 assert.ok(evidence.boot.map&&evidence.boot.muted&&evidence.boot.sound===1);assert.ok(evidence.boot.duration>14&&evidence.boot.duration<16);assert.ok(Math.abs(evidence.boot.videoDuration/evidence.boot.rate-evidence.boot.duration)<.05);
 evidence.camera=await page.evaluate(async()=>{const T=await import('three');return{p:testCamera.position.toArray(),q:testCamera.quaternion.toArray(),bounds:new T.Box3().setFromObject(retro.group).getSize(new T.Vector3()).toArray(),draws:renderer.info.render.calls};});await page.waitForTimeout(2500);assert.equal(await page.evaluate(()=>retro.state),'warm');await page.screenshot({path:path.join(output,'ps1-demarrage-sony.png')});
 await page.waitForFunction(()=>retro.bootVideo.currentTime>10);await page.screenshot({path:path.join(output,'ps1-demarrage-playstation.png')});
 await page.waitForFunction(()=>retro.state==='ready');assert.equal(await page.evaluate(()=>sound.state.startupEvents),1);
 await page.locator('#open').click();await page.waitForFunction(()=>document.querySelector('#retro')?.dataset.view==='menu'&&sound.state.menu);await page.waitForFunction(()=>sound.state.browserEvents===1);
 await page.screenshot({path:path.join(output,'ps1-menu.png')});const before=await page.evaluate(()=>sound.state.actionEvents);
 await page.keyboard.press('ArrowDown');await page.waitForFunction(n=>sound.state.actionEvents>n,before);await page.waitForTimeout(150);
 await page.keyboard.press('ArrowUp');await page.waitForTimeout(150);await page.keyboard.press('Enter');await page.waitForFunction(()=>document.querySelector('#retro').dataset.view==='title');assert.equal(await page.evaluate(()=>sound.state.menu),false);
 await page.keyboard.press('Enter');await page.waitForFunction(()=>document.querySelector('#retro').dataset.view==='play');await page.getByText('RETOUR AU MENU',{exact:true}).click();await page.waitForFunction(()=>sound.state.menu);
 await page.keyboard.press('Escape');await page.waitForFunction(()=>sound.state.exitEvents===1);await page.waitForFunction(()=>!document.querySelector('#retro'));
 evidence.audio=await page.evaluate(()=>({...sound.state}));assert.ok(evidence.audio.actionEvents>=5);assert.equal(evidence.audio.menu,false);
 assert.ok(!requests.some(u=>/ps1-(startup|button|joystick)-v49/.test(u)));assert.deepEqual(errors,[]);
 await page.evaluate(()=>sound.setMuted(true));await writeFile(path.join(output,'ps1-validation.json'),JSON.stringify({...evidence,errors},null,2));console.log('PS1_V50_OK',JSON.stringify(evidence));
}finally{await page.screenshot({path:path.join(output,'ps1-last-state.png')});await writeFile(path.join(output,'ps1-partial.json'),JSON.stringify({...evidence,errors},null,2));await browser.close();}
